# Generated by Django 4.0.4 on 2022-04-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_college_remove_entry_college_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.URLField(default='N/A'),
        ),
    ]
