# Generated by Django 4.0.4 on 2022-04-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_college_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='website',
            new_name='image',
        ),
    ]
