# Generated by Django 4.0.4 on 2022-04-15 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_website_college_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='map.college'),
        ),
    ]
