# Generated by Django 4.0.4 on 2022-04-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_entry_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_anonymous',
        ),
    ]
